name: Integration Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run unit tests
        run: go test ./redactor

      - name: Build Go binary
        run: |
          CGO_ENABLED=0 GOOS=linux go build -a -o container-log-sanitizer main.go

      - name: Prepare plugin rootfs
        run: |
          mkdir -p plugin-rootfs
          cp container-log-sanitizer plugin-rootfs/

      - name: Create plugin config
        run: |
          cat > plugin-rootfs/config.json <<EOF
          {
            "description": "Container log sanitizer plugin",
            "interface": {
              "types": ["docker.logdriver/1.0"],
              "socket": "plugin.sock"
            },
            "entrypoint": ["/container-log-sanitizer"],
            "network": { "type": "host" },
            "mounts": [],
            "env": [
              {
                "name": "SANITIZE_PATTERNS",
                "description": "Regex patterns for log redaction",
                "settable": ["value"],
                "value": ""
              }
            ]
          }
          EOF

      - name: List plugin rootfs contents (debug)
        run: |
          ls -l plugin-rootfs
          file plugin-rootfs/container-log-sanitizer
          cat plugin-rootfs/config.json

      - name: Install Docker plugin (local)
        run: |
          docker plugin rm -f container-log-sanitizer || true
          docker plugin ls
          docker plugin create container-log-sanitizer plugin-rootfs
          docker plugin ls
          docker plugin enable container-log-sanitizer

      - name: Run test container with plugin
        run: |
          docker run --rm --log-driver=container-log-sanitizer -e SANITIZE_PATTERNS='[a-zA-Z]+@example.com' busybox sh -c 'echo "user@example.com"'

      - name: Cleanup plugin
        if: always()
        run: |
          docker plugin disable container-log-sanitizer || true
          docker plugin rm container-log-sanitizer || true
